export type MessageRole = 'user' | 'assistant' | 'system';

import type { AgentTrace } from './agent';

export interface Message {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: Date;
  conversationId: string;
  agentTrace?: AgentTrace;  // Agent trace if this message was generated by agents
}

export interface Conversation {
  id: string;
  title: string;
  createdAt: Date;
  updatedAt: Date;
  messageCount: number;
}

export interface ChatState {
  messages: Message[];
  isLoading: boolean;
  error: string | null;
  isStreaming: boolean;
}

