export type MessageRole = 'user' | 'assistant' | 'system';

import type { AgentTrace } from './agent';

export interface AnalysisState {
  // Analyst Reports
  market_report?: string;
  fundamentals_report?: string;
  sentiment_report?: string;
  news_report?: string;
  information_report?: string;
  
  // Investment Debate
  investment_debate_state?: {
    bull_history?: string;
    bear_history?: string;
    judge_decision?: string;
  };
  
  // Trader Decision
  trader_investment_plan?: string;
  investment_plan?: string;
  
  // Risk Analysis
  risk_debate_state?: {
    risky_history?: string;
    safe_history?: string;
    neutral_history?: string;
    judge_decision?: string;
  };
  
  // Final Decision
  final_trade_decision?: string;
  
  // Any other fields
  [key: string]: any;
}

export interface AgentAnalysis {
  company: string;
  date: string;
  decision: string | null | undefined;
  state: AnalysisState;
}

export interface Message {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: Date;
  conversationId: string;
  agentTrace?: AgentTrace;  // Agent trace if this message was generated by agents
  agentAnalysis?: AgentAnalysis;  // Full agent analysis with state breakdown
}

export interface Conversation {
  id: string;
  title: string;
  createdAt: Date;
  updatedAt: Date;
  messageCount: number;
}

export interface ChatState {
  messages: Message[];
  isLoading: boolean;
  error: string | null;
  isStreaming: boolean;
}

