"""
Execution Plan Models

Defines the data models for LLM Planner execution plans.
"""

from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field


class ExecutionPlan(BaseModel):
    """
    Structured execution plan generated by the LLM Planner.
    
    This plan specifies which agents to execute, in what order,
    and their criticality levels. The orchestrator uses this plan
    to construct the dynamic workflow graph.
    """
    
    agents: List[str] = Field(
        ..., 
        description="List of agent IDs to execute (e.g., ['market_analyst', 'fundamentals_analyst'])"
    )
    execution_order: List[str] = Field(
        ..., 
        description="Ordered list of agent IDs specifying execution sequence. Must match agents list."
    )
    criticality_map: Dict[str, str] = Field(
        ..., 
        description="Mapping of agent_id to criticality level ('critical' or 'non-critical')"
    )
    termination_conditions: Dict[str, Any] = Field(
        default_factory=dict,
        description="Conditions for early termination (optional)"
    )
    
    # Optional metadata
    reasoning: Optional[str] = Field(
        None,
        description="Planner's reasoning for this execution plan"
    )
    estimated_duration: Optional[float] = Field(
        None,
        description="Estimated total execution time in seconds"
    )
    estimated_cost: Optional[float] = Field(
        None,
        description="Estimated total cost"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "agents": ["market_analyst", "fundamentals_analyst", "information_analyst"],
                "execution_order": ["market_analyst", "fundamentals_analyst", "information_analyst"],
                "criticality_map": {
                    "market_analyst": "critical",
                    "fundamentals_analyst": "critical",
                    "information_analyst": "non-critical"
                },
                "termination_conditions": {},
                "reasoning": "Query requires technical and fundamental analysis. Information analysis is supplementary.",
                "estimated_duration": 155.0,
                "estimated_cost": 0.19
            }
        }
    
    def validate(self) -> tuple[bool, Optional[str]]:
        """
        Validate the execution plan structure.
        
        Returns:
            Tuple of (is_valid, error_message)
        """
        # Check that execution_order matches agents
        if set(self.execution_order) != set(self.agents):
            return False, "execution_order must contain exactly the same agents as agents list"
        
        # Check that all agents have criticality assignments
        for agent_id in self.agents:
            if agent_id not in self.criticality_map:
                return False, f"Agent '{agent_id}' missing from criticality_map"
            
            criticality = self.criticality_map[agent_id]
            if criticality not in ["critical", "non-critical"]:
                return False, f"Invalid criticality '{criticality}' for agent '{agent_id}'. Must be 'critical' or 'non-critical'"
        
        return True, None

