"""
Execution Plan Validator

Validates execution plans generated by the LLM Planner to ensure they
reference valid agents from the registry.
"""

from typing import Tuple, Optional
from .models import ExecutionPlan
from agents_module.registry.registry import AgentRegistry


class ExecutionPlanValidator:
    """
    Validates execution plans against the agent registry.
    """
    
    def __init__(self, registry: AgentRegistry):
        """
        Initialize validator.
        
        Args:
            registry: AgentRegistry instance to validate against
        """
        self.registry = registry
    
    def validate(self, plan: ExecutionPlan) -> Tuple[bool, Optional[str]]:
        """
        Validate an execution plan.
        
        Args:
            plan: ExecutionPlan to validate
            
        Returns:
            Tuple of (is_valid, error_message)
        """
        # First, validate plan structure
        is_valid, error = plan.validate()
        if not is_valid:
            return False, error
        
        # Validate that all agents exist in registry
        for agent_id in plan.agents:
            if not self.registry.validate_agent_exists(agent_id):
                return False, f"Agent '{agent_id}' not found in registry"
        
        # Validate dependencies are respected
        for agent_id in plan.agents:
            agent = self.registry.get_agent(agent_id)
            if agent:
                # Check that dependencies appear before this agent in execution_order
                for dep_id in agent.dependencies:
                    if dep_id in plan.agents:
                        agent_index = plan.execution_order.index(agent_id)
                        dep_index = plan.execution_order.index(dep_id)
                        if dep_index >= agent_index:
                            return False, f"Agent '{agent_id}' depends on '{dep_id}' but dependency appears after in execution_order"
        
        return True, None
    
    def validate_and_fix(self, plan: ExecutionPlan) -> Tuple[ExecutionPlan, bool, Optional[str]]:
        """
        Validate plan and attempt to fix common issues.
        
        Args:
            plan: ExecutionPlan to validate and fix
            
        Returns:
            Tuple of (fixed_plan, was_fixed, error_message)
        """
        is_valid, error = self.validate(plan)
        if is_valid:
            return plan, False, None
        
        # Attempt to fix: remove invalid agents
        valid_agents = []
        for agent_id in plan.agents:
            if self.registry.validate_agent_exists(agent_id):
                valid_agents.append(agent_id)
        
        if not valid_agents:
            return plan, False, "No valid agents found in plan"
        
        # Create fixed plan
        fixed_plan = ExecutionPlan(
            agents=valid_agents,
            execution_order=[a for a in plan.execution_order if a in valid_agents],
            criticality_map={k: v for k, v in plan.criticality_map.items() if k in valid_agents},
            termination_conditions=plan.termination_conditions,
            reasoning=plan.reasoning,
            estimated_duration=plan.estimated_duration,
            estimated_cost=plan.estimated_cost
        )
        
        # Validate fixed plan
        is_valid, error = self.validate(fixed_plan)
        if is_valid:
            return fixed_plan, True, None
        else:
            return plan, False, f"Could not fix plan: {error}"

